# Generated by Django 2.2.16 on 2022-08-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220809_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
