# Generated by Django 2.2.16 on 2022-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220809_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ'), ('superuser', 'Суперюзер')], default='user', max_length=20),
        ),
    ]
