# Generated by Django 2.2.16 on 2022-08-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220809_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='email',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
