# Generated by Django 2.2.16 on 2022-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220810_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ'), ('superuser', 'Суперюзер')], max_length=20),
        ),
    ]
