# Generated by Django 2.2.16 on 2022-08-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220810_1727'),
        ('users', '0010_auto_20220810_1227'),
    ]

    operations = [
    ]
