# Generated by Django 2.2.16 on 2022-08-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20220811_0951'),
        ('users', '0012_auto_20220810_1457'),
    ]

    operations = [
    ]
