# Generated by Django 2.2.16 on 2022-08-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220811_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
